FROM macnificos/php-alpine:7.4.16

ARG USER=root
ARG PASSWORD=root

ARG COMPOSER_VERSION=2.2.1

RUN apk add -U --no-cache \
    php7-pear \
    openssh \
    supervisor \
    autoconf \
    git \
    curl \
    wget \
    make \
    zip \
    php7-xdebug \
    # Delete APK cache.
    && rm -rf /var/cache/apk/* \
    # Create ssh user for dev.
    && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
    && echo "${USER}:${PASSWORD}" | chpasswd \
    && ssh-keygen -A \
    # Download composer.
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}

ADD dev-fs /

RUN HOST_IP="$(/sbin/ip route|awk '/default/ { print $3 }')" \
    && sed -i "$ a\xdebug.client_host=${HOST_IP}" /etc/php7/conf.d/00_xdebug.ini

CMD ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord/conf.d/supervisord.conf"]

EXPOSE 22 9000

