name: PR checks

on:
  pull_request:
    branches:
      - master

jobs:
  pr:
    strategy:
      fail-fast: false
      matrix:
        version: [ "7.3", "7.4", "8.0" ]

    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ matrix.version }}
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
         make build
    - name: Run
      run: |
        make run-detached
    - name: Test Main
      run: |
        make test-main